export const themePalettes = {
  light: {
    "--app-bg": "#f4f8fb",
    "--app-surface": "#ffffff",
    "--app-surface-muted": "#f8fbfc",
    "--app-surface-soft": "#eef5f7",
    "--app-border": "rgba(22,50,79,0.08)",
    "--app-border-strong": "rgba(22,50,79,0.18)",
    "--app-text": "#16324f",
    "--app-text-muted": "#5f7890",
    "--app-text-soft": "#35536f",
    "--app-primary": "#0f766e",
    "--app-primary-strong": "#115e59",
    "--app-primary-contrast": "#ffffff",
    "--app-secondary-button-bg": "#ffffff",
    "--app-secondary-button-hover": "#f8fbfc",
    "--app-secondary-button-text": "#16324f",
    "--app-secondary-button-border": "rgba(22,50,79,0.18)",
    "--app-shadow": "0 16px 36px rgba(22,50,79,0.08)",
    "--app-shadow-soft": "0 12px 28px rgba(22,50,79,0.07)",
    "--app-danger-bg": "#fff1f2",
    "--app-danger-text": "#be123c",
    "--app-danger-border": "#fecdd3",
    "--app-error-bg": "#fff1f2",
    "--app-error-text": "#9f1239",
    "--app-error-border": "#fecaca",
    "--app-active-bg": "#dcfce7",
    "--app-active-text": "#166534",
    "--app-inactive-bg": "#fee2e2",
    "--app-inactive-text": "#991b1b",
    "--app-info-bg": "#dbeafe",
    "--app-info-text": "#1d4ed8",
    "--app-info-border": "#93c5fd",
    "--app-neutral-bg": "#e5e7eb",
    "--app-neutral-text": "#374151",
    "--app-neutral-border": "#cbd5e1",
    "--app-badge-border-width": "1px",
    "--app-auth-bg":
      "radial-gradient(circle at top, rgba(14,116,144,0.18), transparent 38%), linear-gradient(180deg, #f3fbfc 0%, #f8fafc 100%)",
    "--app-hero-bg":
      "linear-gradient(135deg, rgba(14,116,144,0.14), rgba(21,128,61,0.14))",
    "--app-drawer-bg": "#f8fbfc",
    "--app-drawer-hover": "rgba(15,118,110,0.08)",
    "--app-appbar-bg": "#16324f",
    "--app-appbar-text": "#ffffff",
    "--app-module-card-base": "#eef5f7",
    "--app-module-card-hover": "#e6f0f4",
    "--app-module-card-title": "#16324f",
    "--app-module-card-description": "#5f7890",
  },
  dark: {
    "--app-bg": "#09131f",
    "--app-surface": "#102133",
    "--app-surface-muted": "#13283d",
    "--app-surface-soft": "#17314b",
    "--app-border": "rgba(148,163,184,0.18)",
    "--app-border-strong": "rgba(148,163,184,0.3)",
    "--app-text": "#e6edf5",
    "--app-text-muted": "#a8bdd2",
    "--app-text-soft": "#c0d0df",
    "--app-primary": "#2dd4bf",
    "--app-primary-strong": "#14b8a6",
    "--app-primary-contrast": "#07221f",
    "--app-secondary-button-bg": "#102133",
    "--app-secondary-button-hover": "#17314b",
    "--app-secondary-button-text": "#e6edf5",
    "--app-secondary-button-border": "rgba(148,163,184,0.3)",
    "--app-shadow": "0 16px 36px rgba(2,6,23,0.4)",
    "--app-shadow-soft": "0 12px 28px rgba(2,6,23,0.36)",
    "--app-danger-bg": "rgba(190,24,93,0.14)",
    "--app-danger-text": "#fda4af",
    "--app-danger-border": "rgba(251,113,133,0.32)",
    "--app-error-bg": "rgba(159,18,57,0.18)",
    "--app-error-text": "#fecdd3",
    "--app-error-border": "rgba(253,164,175,0.28)",
    "--app-active-bg": "rgba(22,163,74,0.18)",
    "--app-active-text": "#86efac",
    "--app-inactive-bg": "rgba(220,38,38,0.18)",
    "--app-inactive-text": "#fca5a5",
    "--app-info-bg": "rgba(37,99,235,0.18)",
    "--app-info-text": "#93c5fd",
    "--app-info-border": "rgba(147,197,253,0.32)",
    "--app-neutral-bg": "rgba(148,163,184,0.18)",
    "--app-neutral-text": "#d1d5db",
    "--app-neutral-border": "rgba(148,163,184,0.28)",
    "--app-badge-border-width": "1px",
    "--app-auth-bg":
      "radial-gradient(circle at top, rgba(45,212,191,0.18), transparent 38%), linear-gradient(180deg, #08111d 0%, #0f1724 100%)",
    "--app-hero-bg":
      "linear-gradient(135deg, rgba(45,212,191,0.14), rgba(59,130,246,0.14))",
    "--app-drawer-bg": "#0c1827",
    "--app-drawer-hover": "rgba(45,212,191,0.14)",
    "--app-appbar-bg": "#0b1827",
    "--app-appbar-text": "#e6edf5",
    "--app-module-card-base": "#1a2a3a",
    "--app-module-card-hover": "#1f3347",
    "--app-module-card-title": "#c8d8e8",
    "--app-module-card-description": "#5a7a9a",
  },
};

export const appShellStyles = {
  page: {
    padding: "clamp(16px, 3vw, 32px)",
    color: "var(--app-text)",
  },
  hero: {
    background: "var(--app-hero-bg)",
    border: "1px solid var(--app-border)",
    borderRadius: "20px",
    padding: "clamp(18px, 3vw, 28px)",
    marginBottom: "clamp(18px, 2vw, 24px)",
    boxShadow: "var(--app-shadow)",
  },
  title: {
    margin: "0 0 10px",
    fontSize: "clamp(1.7rem, 4vw, 2.1rem)",
    lineHeight: 1.1,
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  subtitle: {
    margin: 0,
    maxWidth: "720px",
    color: "var(--app-text-muted)",
    fontSize: "1rem",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    marginTop: "22px",
    alignItems: "stretch",
  },
  actionField: {
    flex: "1 1 240px",
    minWidth: "min(100%, 240px)",
  },
  actionFieldWide: {
    flex: "2 1 320px",
    minWidth: "min(100%, 320px)",
  },
  button: {
    borderRadius: "999px",
    padding: "12px 18px",
    fontSize: "0.95rem",
    fontWeight: 700,
    border: "1px solid transparent",
    maxWidth: "100%",
  },
  primaryButton: {
    backgroundColor: "var(--app-primary)",
    color: "var(--app-primary-contrast)",
  },
  secondaryButton: {
    backgroundColor: "var(--app-secondary-button-bg)",
    color: "var(--app-secondary-button-text)",
    border: "1px solid var(--app-secondary-button-border)",
  },
  infoButton: {
    backgroundColor: "var(--app-info-bg)",
    color: "var(--app-info-text)",
    border: "1px solid var(--app-info-border)",
  },
  neutralButton: {
    backgroundColor: "var(--app-neutral-bg)",
    color: "var(--app-neutral-text)",
    border: "1px solid var(--app-neutral-border)",
  },
  dangerButton: {
    backgroundColor: "var(--app-danger-bg)",
    color: "var(--app-danger-text)",
    border: "1px solid var(--app-danger-border)",
  },
  card: {
    backgroundColor: "var(--app-surface)",
    borderRadius: "20px",
    border: "1px solid var(--app-border)",
    boxShadow: "var(--app-shadow)",
    padding: "clamp(18px, 2.5vw, 24px)",
    minWidth: 0,
  },
  cardFill: {
    minHeight: "100%",
  },
  sectionTitle: {
    margin: "0 0 8px",
    fontSize: "1.08rem",
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  sectionText: {
    margin: "0 0 20px",
    color: "var(--app-text-muted)",
    fontSize: "0.94rem",
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 240px), 1fr))",
    gap: "16px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  fieldFull: {
    gridColumn: "1 / -1",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "0.92rem",
    fontWeight: 700,
    color: "var(--app-text-soft)",
  },
  helperText: {
    margin: "-2px 0 0",
    fontSize: "0.84rem",
    color: "var(--app-text-muted)",
  },
  infoBox: {
    marginBottom: "18px",
    padding: "14px 16px",
    borderRadius: "16px",
    border: "1px solid var(--app-border)",
    backgroundColor: "var(--app-surface-muted)",
    color: "var(--app-text-muted)",
    lineHeight: 1.6,
  },
  input: {
    borderRadius: "14px",
    border: "1px solid var(--app-border-strong)",
    padding: "12px 14px",
    fontSize: "0.95rem",
    color: "var(--app-text)",
    backgroundColor: "var(--app-surface-muted)",
    width: "100%",
    boxSizing: "border-box",
  },
  textarea: {
    borderRadius: "14px",
    border: "1px solid var(--app-border-strong)",
    padding: "12px 14px",
    fontSize: "0.95rem",
    color: "var(--app-text)",
    backgroundColor: "var(--app-surface-muted)",
    minHeight: "160px",
    resize: "vertical",
    width: "100%",
    boxSizing: "border-box",
  },
  checkboxRow: {
    marginTop: "18px",
    padding: "14px 16px",
    borderRadius: "16px",
    backgroundColor: "var(--app-surface-muted)",
    border: "1px solid var(--app-border)",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: 600,
    color: "var(--app-text-soft)",
  },
  footerActions: {
    display: "flex",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: "12px",
    marginTop: "24px",
    alignItems: "stretch",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  statCard: {
    backgroundColor: "var(--app-surface)",
    borderRadius: "18px",
    border: "1px solid var(--app-border)",
    boxShadow: "var(--app-shadow-soft)",
    padding: "20px",
    minWidth: 0,
  },
  statAccentCard: {
    background:
      "linear-gradient(135deg, rgba(15,118,110,0.1), rgba(14,116,144,0.1))",
    borderColor: "var(--app-border-strong)",
  },
  statLabel: {
    margin: 0,
    color: "var(--app-text-muted)",
    fontSize: "0.92rem",
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  statValue: {
    margin: "8px 0 0",
    fontSize: "clamp(1.45rem, 3vw, 1.8rem)",
    fontWeight: 800,
    lineHeight: 1.2,
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  listStack: {
    display: "grid",
    gap: "10px",
  },
  listRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    padding: "12px 14px",
    borderRadius: "14px",
    backgroundColor: "var(--app-surface-muted)",
    border: "1px solid var(--app-border)",
  },
  listRowLabel: {
    color: "var(--app-text-soft)",
    fontWeight: 600,
    flex: "1 1 auto",
    minWidth: 0,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  tableCard: {
    backgroundColor: "var(--app-surface)",
    borderRadius: "20px",
    border: "1px solid var(--app-border)",
    boxShadow: "var(--app-shadow)",
    overflow: "hidden",
  },
  tableHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "12px",
    padding: "clamp(16px, 2.5vw, 20px)",
    borderBottom: "1px solid var(--app-border)",
    backgroundColor: "var(--app-surface-muted)",
  },
  tableTitle: {
    margin: 0,
    fontSize: "1.05rem",
  },
  tableMeta: {
    margin: "4px 0 0",
    color: "var(--app-text-muted)",
    fontSize: "0.92rem",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "12px",
    marginBottom: "20px",
  },
  summaryCard: {
    padding: "14px 16px",
    borderRadius: "16px",
    border: "1px solid var(--app-border)",
    backgroundColor: "var(--app-surface-muted)",
    minWidth: 0,
  },
  summaryLabel: {
    margin: 0,
    fontSize: "0.82rem",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--app-text-muted)",
  },
  summaryValue: {
    margin: "6px 0 0",
    fontSize: "1rem",
    fontWeight: 700,
    color: "var(--app-text)",
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  summaryValueSoft: {
    color: "var(--app-text-soft)",
    fontWeight: 600,
  },
  tableHeaderActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  inlineStatus: {
    width: "100%",
    marginTop: "4px",
    fontSize: "0.82rem",
    color: "var(--app-text-muted)",
  },
  inlineStatusSuccess: {
    color: "var(--app-active-text)",
  },
  inlineStatusError: {
    color: "var(--app-error-text)",
  },
  tableActionGroup: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  tableActionButton: {
    padding: "9px 14px",
    fontSize: "0.88rem",
  },
  tableWrap: {
    overflowX: "auto",
  },
  mobileCards: {
    display: "grid",
    gap: "14px",
    padding: "16px",
  },
  mobileCard: {
    border: "1px solid var(--app-border)",
    borderRadius: "18px",
    backgroundColor: "var(--app-surface-muted)",
    padding: "16px",
    boxShadow: "var(--app-shadow-soft)",
    minWidth: 0,
  },
  mobileCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
    marginBottom: "14px",
  },
  mobileCardTitle: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 700,
    color: "var(--app-text)",
  },
  mobileCardMeta: {
    margin: "6px 0 0",
    fontSize: "0.84rem",
    color: "var(--app-text-muted)",
  },
  mobileCardGrid: {
    display: "grid",
    gap: "12px",
  },
  mobileCardRow: {
    display: "grid",
    gap: "4px",
  },
  mobileCardLabel: {
    margin: 0,
    fontSize: "0.78rem",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--app-text-muted)",
  },
  mobileCardValue: {
    margin: 0,
    fontSize: "0.94rem",
    color: "var(--app-text)",
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  mobileCardActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginTop: "16px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "max(640px, 100%)",
  },
  th: {
    textAlign: "left",
    padding: "14px 16px",
    backgroundColor: "var(--app-surface-soft)",
    color: "var(--app-text-soft)",
    fontSize: "0.88rem",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  td: {
    padding: "14px 16px",
    borderTop: "1px solid var(--app-border)",
    fontSize: "0.95rem",
    color: "var(--app-text)",
    verticalAlign: "top",
  },
  badge: {
    display: "inline-block",
    borderRadius: "999px",
    padding: "4px 10px",
    fontSize: "0.8rem",
    fontWeight: 700,
    border: "var(--app-badge-border-width) solid transparent",
  },
  activeBadge: {
    backgroundColor: "var(--app-active-bg)",
    color: "var(--app-active-text)",
    borderColor: "var(--app-active-bg)",
  },
  inactiveBadge: {
    backgroundColor: "var(--app-inactive-bg)",
    color: "var(--app-inactive-text)",
    borderColor: "var(--app-inactive-bg)",
  },
  infoBadge: {
    backgroundColor: "var(--app-info-bg)",
    color: "var(--app-info-text)",
    borderColor: "var(--app-info-border)",
  },
  neutralBadge: {
    backgroundColor: "var(--app-neutral-bg)",
    color: "var(--app-neutral-text)",
    borderColor: "var(--app-neutral-border)",
  },
  emptyState: {
    padding: "28px 20px",
    color: "var(--app-text-muted)",
  },
  emptyStateCard: {
    marginTop: "20px",
    padding: "24px 20px",
    borderRadius: "18px",
    border: "1px dashed var(--app-border-strong)",
    backgroundColor: "var(--app-surface-muted)",
    color: "var(--app-text-muted)",
    textAlign: "center",
  },
  emptyStateTitle: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 700,
    color: "var(--app-text)",
  },
  emptyStateText: {
    margin: "8px 0 0",
    fontSize: "0.94rem",
    lineHeight: 1.6,
  },
  loadingCard: {
    padding: "24px 20px",
    borderRadius: "18px",
    border: "1px solid var(--app-border)",
    backgroundColor: "var(--app-surface-muted)",
    color: "var(--app-text-muted)",
  },
  errorBox: {
    marginBottom: "20px",
    borderRadius: "16px",
    border: "1px solid var(--app-error-border)",
    backgroundColor: "var(--app-error-bg)",
    color: "var(--app-error-text)",
    padding: "14px 16px",
  },
  successBox: {
    marginBottom: "20px",
    borderRadius: "16px",
    border: "1px solid var(--app-active-bg)",
    backgroundColor: "var(--app-active-bg)",
    color: "var(--app-active-text)",
    padding: "14px 16px",
  },
  authPage: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    padding: "clamp(16px, 4vw, 32px)",
    background: "var(--app-auth-bg)",
  },
  authCard: {
    width: "100%",
    maxWidth: "430px",
    backgroundColor: "var(--app-surface)",
    borderRadius: "24px",
    border: "1px solid var(--app-border)",
    boxShadow: "0 24px 60px rgba(2,6,23,0.18)",
    padding: "clamp(20px, 5vw, 30px)",
  },
};
