from sqlalchemy import inspect, text


def ensure_audit_schema_compatibility(engine) -> None:
    inspector = inspect(engine)
    table_names = inspector.get_table_names()

    dialect = engine.dialect.name

    index_statements = [
        "CREATE INDEX IF NOT EXISTS ix_audit_events_id ON audit_events (id)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_actor_user_id ON audit_events (actor_user_id)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_target_user_id ON audit_events (target_user_id)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_module ON audit_events (module)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_action ON audit_events (action)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_resource_type ON audit_events (resource_type)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_resource_id ON audit_events (resource_id)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_status ON audit_events (status)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_ip_address ON audit_events (ip_address)",
        "CREATE INDEX IF NOT EXISTS ix_audit_events_created_at ON audit_events (created_at)",
    ]

    with engine.begin() as connection:
        if "audit_events" not in table_names:
            if dialect == "postgresql":
                connection.execute(
                    text(
                        """
                        CREATE TABLE IF NOT EXISTS audit_events (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            actor_user_id INTEGER,
                            target_user_id INTEGER,
                            module VARCHAR(50) NOT NULL,
                            action VARCHAR(80) NOT NULL,
                            resource_type VARCHAR(80) NOT NULL,
                            resource_id VARCHAR(80),
                            status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
                            ip_address VARCHAR(64),
                            details TEXT,
                            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            FOREIGN KEY(actor_user_id) REFERENCES users (id),
                            FOREIGN KEY(target_user_id) REFERENCES users (id)
                        )
                        """
                    )
                )
            else:
                connection.execute(
                    text(
                        """
                        CREATE TABLE audit_events (
                            id INTEGER PRIMARY KEY,
                            actor_user_id INTEGER,
                            target_user_id INTEGER,
                            module VARCHAR(50) NOT NULL,
                            action VARCHAR(80) NOT NULL,
                            resource_type VARCHAR(80) NOT NULL,
                            resource_id VARCHAR(80),
                            status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
                            ip_address VARCHAR(64),
                            details TEXT,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            FOREIGN KEY(actor_user_id) REFERENCES users (id),
                            FOREIGN KEY(target_user_id) REFERENCES users (id)
                        )
                        """
                    )
                )
        elif dialect == "postgresql":
            connection.execute(text("CREATE SEQUENCE IF NOT EXISTS audit_events_id_seq"))
            connection.execute(
                text(
                    """
                    ALTER TABLE audit_events
                    ALTER COLUMN id SET DEFAULT nextval('audit_events_id_seq')
                    """
                )
            )
            connection.execute(
                text(
                    """
                    SELECT setval(
                        'audit_events_id_seq',
                        GREATEST(COALESCE((SELECT MAX(id) FROM audit_events), 0) + 1, 1),
                        false
                    )
                    """
                )
            )
        for statement in index_statements:
            connection.execute(text(statement))
