CREATE SCHEMA IF NOT EXISTS rh;
CREATE SCHEMA IF NOT EXISTS inteligencia;
CREATE SCHEMA IF NOT EXISTS estatistica;
CREATE SCHEMA IF NOT EXISTS logistica;
CREATE SCHEMA IF NOT EXISTS relacoes_publicas;
CREATE SCHEMA IF NOT EXISTS uge;
CREATE SCHEMA IF NOT EXISTS stcor;
CREATE SCHEMA IF NOT EXISTS telematica;
