export const MARITAL_STATUS_OPTIONS = [
  "Solteiro(a)",
  "Casado(a)",
  "Uniao estavel",
  "Divorciado(a)",
  "Viuvo(a)",
];

export const NATURALITY_OPTIONS = [
  "Acre",
  "Alagoas",
  "Amapa",
  "Amazonas",
  "Bahia",
  "Ceara",
  "Distrito Federal",
  "Espirito Santo",
  "Goias",
  "Maranhao",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Para",
  "Paraiba",
  "Parana",
  "Pernambuco",
  "Piaui",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondonia",
  "Roraima",
  "Santa Catarina",
  "Sao Paulo",
  "Sergipe",
  "Tocantins",
];

export const RANK_OPTIONS = [
  "Cel PM",
  "Ten Cel PM",
  "Maj PM",
  "Cap PM",
  "1 Ten PM",
  "2 Ten PM",
  "Asp OF PM",
  "Subten PM",
  "1 Sgt PM",
  "2 Sgt PM",
  "3 Sgt PM",
  "Cb PM",
  "Sd PM 1 Cl",
  "Sd PM 2 Cl",
  "Civil",
];

export const SEXUAL_ORIENTATION_OPTIONS = [
  "Heterossexual",
  "Gay",
  "Lesbica",
  "Bissexual",
  "Pansexual",
  "Assexual",
  "Outra",
  "Prefiro não informar",
];

export const OTHER_CITY_OPTION = "__OUTRA_CIDADE__";
export const OTHER_UNIT_OPTION = "__OUTRA_UNIDADE__";
export const OTHER_STATE_OPTION = "__OUTRO_ESTADO__";

export const STATE_OPTIONS = [
  "Acre",
  "Alagoas",
  "Amapa",
  "Amazonas",
  "Bahia",
  "Ceara",
  "Distrito Federal",
  "Espirito Santo",
  "Goias",
  "Maranhao",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Para",
  "Paraiba",
  "Parana",
  "Pernambuco",
  "Piaui",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondonia",
  "Roraima",
  "Santa Catarina",
  "Sao Paulo",
  "Sergipe",
  "Tocantins",
];
