from app.shared.utils.cpf import normalize_cpf
from app.shared.utils.scope import (
    MODULE_P1,
    MODULE_P4,
    MODULE_TELEMATICA,
    apply_movement_unit_scope,
    apply_unit_scope,
    can_access_unit,
    can_manage_users_in_unit,
    collect_descendant_unit_ids,
    collect_descendant_unit_ids_from_db,
    filter_movements_by_unit_ids,
    get_accessible_unit_ids,
    require_module_access,
    require_unit_access,
    resolve_filter_unit_ids,
    resolve_unit_id_for_creation,
    user_has_global_scope,
    user_has_module_access,
    user_is_unit_admin,
)

__all__ = [
    "MODULE_P1",
    "MODULE_P4",
    "MODULE_TELEMATICA",
    "apply_movement_unit_scope",
    "apply_unit_scope",
    "can_access_unit",
    "can_manage_users_in_unit",
    "collect_descendant_unit_ids",
    "collect_descendant_unit_ids_from_db",
    "filter_movements_by_unit_ids",
    "get_accessible_unit_ids",
    "normalize_cpf",
    "require_module_access",
    "require_unit_access",
    "resolve_filter_unit_ids",
    "resolve_unit_id_for_creation",
    "user_has_global_scope",
    "user_has_module_access",
    "user_is_unit_admin",
]
