export const FLEET_HOLDER_OPTIONS = ["DER", "PMESP", "CONCESSIONÁRIA"];

export const FLEET_SITUATION_OPTIONS = [
  "Operando",
  "Reserva",
  "Baixa Mecânica",
  "Processo de descarga",
];

export const FLEET_CONTRACT_TERM_OPTIONS = ["48 meses", "36 meses", "24 meses", "12 meses", "Outro"];

export const FLEET_EMPLOYMENT_OPTIONS = [
  "Comandante",
  "Sub Cmt",
  "CoordOp",
  "Cmt de Cia",
  "Cmt de Pel",
  "Operacional",
  "Administrativo",
];

export const FLEET_COLOR_OPTIONS = [
  "Branco",
  "Preto",
  "Prata",
  "Cinza",
  "Grafite",
  "Azul",
  "Azul Marinho",
  "Vermelho",
  "Bordô",
  "Verde",
  "Bege",
  "Marrom",
  "Amarelo",
  "Laranja",
  "Dourado",
  "Champagne",
  "Vinho",
  "Roxo",
  "Outro",
];

export const FLEET_FUEL_OPTIONS = [
  "Gasolina",
  "Etanol",
  "Flex",
  "Diesel",
  "Elétrico",
  "Híbrido",
  "GNV",
  "Outro",
];

export const FLEET_WHEEL_OPTIONS = [
  { value: "4", label: "4 Rodas (Automóvel/Camioneta/Caminhonete)" },
  { value: "2", label: "2 Rodas (Motocicleta)" },
];

export const FLEET_GROUP_OPTIONS = [
  "3. TRANSPORTE MISTO",
  "8. VEÍCULO SERVIÇO RESERVADO",
  "11. ROCAM",
  "19. MOTO ESTAFETA",
  "20. FT (TOR)",
  "21. Patrulha",
  "21. RP Rv Est",
  "21. RP",
  "21. CMT BTL",
  "21. CMT CIA",
  "21. COP (Coord Op)",
  "21. CFP",
  "21. CGP",
  "21. APOIO BOP",
  "22. TRANSPORTE PESSOAL",
];

export const FLEET_TELEMETRY_OPTIONS = ["Sim", "Não"];

export const FLEET_BRAND_OPTIONS = {
  "4": [
    "Agrale",
    "Audi",
    "BMW",
    "BYD",
    "Caoa Chery",
    "Chevrolet",
    "Citroën",
    "DAF",
    "Fiat",
    "Ford",
    "GWM/Haval",
    "Honda",
    "Hyundai",
    "JAC",
    "Jeep",
    "Kia",
    "Land Rover",
    "Lexus",
    "Lifan",
    "MAN",
    "Mercedes-Benz",
    "Mitsubishi",
    "Nissan",
    "Peugeot",
    "RAM",
    "Renault",
    "Scania",
    "Subaru",
    "Suzuki",
    "Toyota",
    "Troller",
    "Volkswagen",
    "Volvo",
    "Outros",
  ],
  "2": [
    "Dafra",
    "Honda",
    "Kawasaki",
    "Haojue",
    "Royal Enfield",
    "Shineray",
    "Sundown",
    "Suzuki",
    "Triumph",
    "TVS",
    "Yamaha",
    "BMW Motorrad",
    "Ducati",
    "Harley-Davidson",
    "KTM",
    "Outros",
  ],
};

export const FLEET_MODEL_OPTIONS_BY_BRAND = {
  Toyota: ["Hilux", "Corolla", "Yaris", "SW4", "RAV4", "Prius", "Etios", "Outros"],
  Chevrolet: ["S10", "Onix", "Tracker", "Spin", "Trailblazer", "Montana", "Outros"],
  Ford: ["Ranger", "Ka", "Territory", "Bronco Sport", "Maverick", "Outros"],
  Volkswagen: ["Amarok", "Polo", "Virtus", "T-Cross", "Saveiro", "Gol", "Outros"],
  Fiat: ["Strada", "Toro", "Pulse", "Mobi", "Argo", "Cronos", "Ducato", "Outros"],
  Hyundai: ["HB20", "Creta", "Tucson", "Santa Fe", "Outros"],
  Jeep: ["Compass", "Renegade", "Commander", "Wrangler", "Outros"],
  Mitsubishi: ["L200", "Outlander", "Eclipse Cross", "Pajero", "Outros"],
  Nissan: ["Frontier", "Kicks", "Versa", "Outros"],
  Renault: ["Duster", "Kwid", "Sandero", "Oroch", "Logan", "Outros"],
  Honda: [
    "HR-V",
    "City",
    "Fit",
    "WR-V",
    "CG 160",
    "CB 300",
    "XRE 300",
    "PCX 150",
    "Biz 125",
    "Pop 110",
    "Outros",
  ],
  Kia: ["Sportage", "Sorento", "Stinger", "Outros"],
  BMW: ["X1", "X3", "X5", "Série 3", "Outros"],
  "Mercedes-Benz": ["Classe C", "GLA", "GLC", "Sprinter", "Actros", "Outros"],
  Scania: ["R-Series", "S-Series", "Outros"],
  Volvo: ["FH", "FM", "FMX", "Outros"],
  BYD: ["Dolphin", "Seal", "Han", "Tan", "Outros"],
  "GWM/Haval": ["H6", "Jolion", "H5", "Outros"],
  Peugeot: ["208", "2008", "3008", "Expert", "Outros"],
  Citroën: ["C3", "Aircross", "Jumper", "Outros"],
  RAM: ["1500", "2500", "700", "Outros"],
  Yamaha: ["Factor 150", "Fazer 250", "MT-03", "NMAX", "Crosser 150", "Outros"],
  Suzuki: ["GSX-S750", "V-Strom", "Burgman", "Outros"],
  Kawasaki: ["Z400", "Ninja 400", "Versys", "Outros"],
  Dafra: ["Apache", "Speed", "Laser", "Outros"],
  Haojue: ["NK 150", "DR 160", "Outros"],
};
